export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const ERROR_LOGIN = "ERROR_LOGIN";
export const LOADING_LOGIN = "LOADING_LOGIN";
export const AUTH_USER_LOADING = "AUTH_USER_LOADING";
export const AUTH_USER_ERROR = "AUTH_USER_ERROR";
export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
